# SonarQube Configuration
sonar.projectKey=ltreze_poc-result-pattern
sonar.organization=ltreze

# Source directories
sonar.sources=./src
sonar.tests=./src

# Language
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/TestResults.xml

# Exclusions (adjust as needed)
sonar.coverage.exclusions=**/Program.cs,**/Migrations/**,**/bin/**,**/obj/**
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**

# Code Analysis
sonar.cs.analyzer.projectOutPaths=**/bin/**,**/obj/**
