name: Esteira DEV

on:
  push:
    branches:
      - develop
      - feature/**
      - ci/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup .NET V4
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Install Coverlet
      run: dotnet tool install --global coverlet.console

    - name: Install Amazon.Lambda.Tools
      run: |
        dotnet tool install -g Amazon.Lambda.Tools
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: Install SonarScanner for .NET
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Add .NET tools to PATH
      run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

    - name: SonarCloud Begin
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        dotnet sonarscanner begin \
          /k:"leonardo-souza-dev_poc-result-pattern" \
          /o:"ltreze" \
          /d:sonar.login="$SONAR_TOKEN" \
          /d:sonar.cs.opencover.reportsPaths="coverage-results/coverage.json"

    - name: Restore and Build 
      run: |
        dotnet restore ./src/FooSolution.sln
        dotnet build ./src/FooSolution.sln --configuration Release --no-restore

    - name: Test with Coverage
      run: |
        dotnet test ./src/FooSolution.sln --no-build --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=json /p:CoverletOutput=coverage-results/coverage.json

    - name: SonarCloud End
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN"
